config/routes.rb
Rails.application.routes.draw do
  # get 'orders/index'
  # get 'orders/show'
  # get 'orders/new'
  # get 'carts/show'
  devise_for :users
  root to: 'pages#home'


  get 'carts/:id', to: "carts#show", as: "cart"
  delete 'carts/:id', to: "carts#destroy"

  post 'cart_candles/:id/add', to: 'cart_candles#add_quantity', as: 'cart_candle_add'
  post 'cart_candles/:id/reduce', to: 'cart_candles#reduce_quantity', as: 'cart_candle_reduce'
  post 'cart_candles', to: 'cart_candle#create'

  get 'cart_candles/:id', to: "create_candles#show", as: "cart_candle"
  delete "cart_candles/:id", to: "cart_candles#destroy"

  resources :candles
  resources :orders
  resources :pages


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candle.rb
class Candle < ApplicationRecord
  has_many :cart_candles, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_candles, dependent: :destroy
  has_many :candles, through: :cart_candles

  def sub_total
    sum = 0
    self.cart_candles.each do |cart_candle|
      sum+= cart_candle.total_price
    end
    return sum
  end

end

app/models/cart_candle.rb
class CartCandle < ApplicationRecord
  belongs_to :candle
  belongs_to :cart
  belongs_to :order


  def total_price
    self.quantity * self.product.price
  end

  def create
  # Find associated product and current cart
  chosen_product = Candle.find(params[:candle_id])
  current_cart = @current_cart

  # If cart already has this product then find the relevant cart_candle and iterate quantity otherwise create a new cart_candle for this product
  if current_cart.candles.include?(chosen_product)
    # Find the cart_candle with the chosen_product
    @cart_candle = current_cart.cart_candles.find_by(:candle_id => chosen_product)
    # Iterate the cart_candle's quantity by one
    @cart_candle.quantity += 1
  else
    @cart_candle = CartCandle.new
    @cart_candle.cart = current_cart
    @cart_candle.candle = chosen_product
  end

  # Save and redirect to cart show path
  @cart_candle.save
  redirect_to cart_path(current_cart)
end

private
  def cart_candle_params
    params.require(:cart_candle).permit(:quantity,:candle_id, :cart_id)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :cart_candles, dependent: :destroy

  def create
    @order = Order.new(order_params)
    @current_cart.cart_candles. each do |item|
      @order.cart_candles << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  # before_action :current_cart
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :current_cart

  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
      end
    end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :email, :password])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :email, :password])
  end

end

app/controllers/candles_controller.rb
class CandlesController < ApplicationController
   skip_before_action :authenticate_user!, only: [ :index ]

  def index
    @candle = Candle.all
  end

  def new
    @candle = Candle.new
  end

  def create
    @candle = Candle.create(candle_params)
    redirect_to candles_path
  end

   def edit
    @candle = Candle.find(params[:id])
   end

   def update
    @candle = Candle.find(params[:id])
    @candle.update(candle_params)
    redirect_to candles_path
   end

   def destroy
    @candle = Candle.find(params[:id])
    @candle.destroy
    redirect_to candles_path
   end

   private
    def candle_params
    params.require(:candle).permit(:name, :price)
   end

  # def show
  #   @candle = Candle.find(params[:id])
  # end

end
# a user has many carts
# a cart has one user
# a cart has many cart candles
# a cart candle has one cart
# a cart candle has one candle
# a candle has many cart candles
#

app/controllers/cart_candles_controller.rb
class CartCandlesController < ApplicationController

  def destroy
  @cart_candle = CartCandle.find(params[:id])
  @cart_candle.destroy
  redirect_to cart_path(@current_cart)
  end

  def add_quantity
    @cart_candle = CartCandle.find(params[:id])
    @cart_candle.quantity += 1
    @cart_candle.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @cart_candle = CartCandle.find(params[:id])
    if @cart_candle.quantity > 1
      @cart_candle.quantity -= 1
    end
    @cart_candle.save
    redirect_to cart_cath(@current_cart)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candles/index.html.erb
button_to "Add to cart", cart_candles_path(:candle_id => candle.id)
<h2>All candles</h2>

<% @candles.each do |candle| %>
  <p>Name: <%= candle.name %>; unit price of <%= number_to_currency(candle.price) %></p>
  <p>
    <%= link_to "Edit", edit_candle_path(candle) %> |
    <%= link_to "Delete", candle_path(candle), method: :delete, data: {confirm: "Are you sure?"} %>
    <%= button_to "Add #{candle.name} to cart", cart_candles_path(:candle_id => candle.id) %>
  </p>
<% end%>

<%= link_to "New candle", new_candle_path %>
<%= button_to "Add #{candle.name} to cart", cart_candles_path(:candle_id => candle.id) %>

app/views/cart_candles/index.html.erb
<%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
<%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>

app/views/carts/show.html.erb
<h2>Cart show</h2>
<ul>
  <% @cart.cart_candles.each do |cart_candle| %>
    <li>Item: <%= cart_candle.candle.name %>/ Price: <%= number_to_currency(cart_candle.candle.price) %>/ Quantity: <%= cart_candle.quantity %>/ Total Price: <%= number_to_currency(cart_candle.total_price) %>
    <ul>
      <li>
        <%= link_to "Add one", cart_candle_add_path(:id => cart_candle), method: :post %>
        <%= link_to "Reduce one", cart_candle_reduce_path(:id => cart_candle), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", cart_candle_path(cart_candle), method: :delete %>
      </li>
    </ul>
    #
  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
<%= link_to "Proceed to checkout", new_order_path %> <br>
<%= link_to "Empty cart", cart_path(@current_cart), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h2>All Orders</h2>

<% @orders.each do |order| %>
  <p> Name: <%= order.name %> </p>
  <p> Email: <%= order.email %> </p>
  <p>Cart Candles: </p>
  <ul>
    <% order.cart_candles.each do |item| %>
      <li><%= item.quantity %> x <%= item.candle.name %> </li>
    <% end %>
  </ul>
<% end %>

app/views/orders/new.html.erb
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.label :text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :address %> <br>
    <%= f.label :text_area :address %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pages/about.html.erb
<h1>about meeee test</h1>

<%= <%= image_tag "source", alt: "alttext" %> %>
<%= link_to ,  %>

app/views/pages/home.html.erb
<h1>CANDLES FOREVER HEAUX!</h1>
<h3>I'll take ya to the candle shop</h3>


<% if user_signed_in? %>
  <%= current_user.email %>
<% end %>

app/views/shared/_candle_edit.html.erb
<%= form_for(@candle) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter candle name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end

app/views/shared/_candle_new.html.erb
<%= form_for(@candle) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter candle name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>